# Machine Learning Assignment (Semester 252)

In [2]:
import os

# Repo information
GIT_REPO = "ML-Assignment"
GIT_PATH = f"https://github.com/phngan05/ML-Assignment.git"

# Check if the repository already exists, if not clone it. If it exists, pull the latest changes.
%cd /content
if not os.path.exists(GIT_REPO):
    !git clone {GIT_PATH}
    %cd {GIT_REPO}
else:
    %cd {GIT_REPO}
    !git pull origin main

/content
/content/ML-Assignment
From https://github.com/phngan05/ML-Assignment
 * branch            main       -> FETCH_HEAD
Already up to date.

In [3]:
!pip install -r requirements.txt

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 1)) (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 2)) (2.2.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 3)) (1.6.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 4)) (3.10.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 5)) (0.13.2)
Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 6)) (1.7.4.5)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 7)) (3.9.1)
Requirement already satisfied: wordcloud in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 8)) (1.9.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->-r requirements.txt (line 2)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->-r requirements.txt (line 2)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->-r requirements.txt (line 2)) (2025.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->-r requirements.txt (line 3)) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->-r requirements.txt (line 3)) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->-r requirements.txt (line 3)) (3.6.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 4)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 4)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 4)) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 4)) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 4)) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 4)) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 4)) (3.3.2)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle->-r requirements.txt (line 6)) (6.3.0)
Requirement already satisfied: certifi>=14.05.14 in /usr/local/lib/python3.12/dist-packages (from kaggle->-r requirements.txt (line 6)) (2026.2.25)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.12/dist-packages (from kaggle->-r requirements.txt (line 6)) (3.4.4)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from kaggle->-r requirements.txt (line 6)) (3.11)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle->-r requirements.txt (line 6)) (5.29.6)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle->-r requirements.txt (line 6)) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle->-r requirements.txt (line 6)) (2.32.4)
Requirement already satisfied: setuptools>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from kaggle->-r requirements.txt (line 6)) (75.2.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.12/dist-packages (from kaggle->-r requirements.txt (line 6)) (1.17.0)
Requirement already satisfied: text-unidecode in /usr/local/lib/python3.12/dist-packages (from kaggle->-r requirements.txt (line 6)) (1.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle->-r requirements.txt (line 6)) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle->-r requirements.txt (line 6)) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from kaggle->-r requirements.txt (line 6)) (0.5.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk->-r requirements.txt (line 7)) (8.3.1)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk->-r requirements.txt (line 7)) (2025.11.3)

In [4]:
# Download the dataset
from modules import utils
utils.setup_data("blessondensil294/topic-modeling-for-research-articles")

--- Setting up Kaggle API and downloading data... ---
--- Data downloaded successfully into 'data' ---

In [5]:
# Use for check /content directory structure in VSCode
!ls -R /content

/content:
ML-Assignment  sample_data

/content/ML-Assignment:
data  modules  notebooks  README.md  requirements.txt

/content/ML-Assignment/data:
test.csv  train.csv

/content/ML-Assignment/modules:
eda.py	evaluation.py  model.py  preprocessing.py  __pycache__	utils.py

/content/ML-Assignment/modules/__pycache__:
utils.cpython-312.pyc

/content/ML-Assignment/notebooks:
main.ipynb

/content/sample_data:
anscombe.json		      mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md

In [6]:
!cat /content/ML-Assignment/modules/eda.py

import numpy as np
from nltk.tokenize import sent_tokenize
import matplotlib.pyplot as plt
import seaborn as sns


def calculate_text_lengths(df, column_name):
    """
    Calculates the necessary lengths in a specified text column.
    """
    # Calculate the number of characters (including spaces)
    df[f'{column_name}_chars'] = df[column_name].str.len()

    # Calculate the number of words (split by spaces)
    df[f'{column_name}_words'] = df[column_name].apply(lambda x: len(str(x).split()))

    # Calculate the mean word length
    df[f'{column_name}_mean_word_length'] = df[f'{column_name}_chars'] / df[f'{column_name}_words']

    # Calculate mean sentence length
    df[f'{column_name}_mean_sentence_length'] = df[column_name].map(lambda x: np.mean([len(sent) for sent in sent_tokenize(str(x))]))

    return df

def visualize_text_length_distribution(df, column_name):
    """
    Visualize the distribution of text lengths using boxplot and histogram.
    """
    fig, axes = plt.subplots(1, 2, figsize=(12, 4))
    sns.boxplot(y = df[column_name], color="red", ax=axes[0])
    sns.histplot(df[column_name], color="skyblue", kde=True, ax=axes[1])
    fig.suptitle(f'Distribution of {column_name}', fontsize=16)
    plt.show()

In [7]:
import pandas as pd
df = pd.read_csv("/content/ML-Assignment/data/train.csv")
df.head()

,ID,TITLE,ABSTRACT,Computer Science,Physics,Mathematics,Statistics,Quantitative Biology,Quantitative Finance
0,1,Reconstructing Subject-Specific Effect Maps,Predictive models allow subject-specific inf...,1,0,0,0,0,0
1,2,Rotation Invariance Neural Network,Rotation invariance and translation invarian...,1,0,0,0,0,0
2,3,Spherical polyharmonics and Poisson kernels fo...,We introduce and develop the notion of spher...,0,0,1,0,0,0
3,4,A finite element approximation for the stochas...,The stochastic Landau--Lifshitz--Gilbert (LL...,0,0,1,0,0,0
4,5,Comparative study of Discrete Wavelet Transfor...,Fourier-transform infra-red (FTIR) spectra o...,1,0,0,1,0,0

## Exploratory Data Analysis

### Length Analysis

Visualize by Boxplot and Histogram for TITLE

### Title
1. Title characters
- Statistics: Mean ~ 73, Median: 71, IQR: 54–88, Range: 7–239.
- Distribution: Slightly right-skewed; most titles fall within 50–90 characters.
- Outliers: Several upper outliers indicate a subset of unusually lengthy titles.
- Insight: Titles are generally concise, but exhibit high variance in maximum length.

2. Title words
- Statistics: Mean ~ 9.5, Median: 9, IQR: 7-12, Range: 1-40 words
- Distribution: Slightly right-skewed; dense concentration between 5 and 15 words
- Outliers: Upper outliers suggest the inclusion of descriptive or multi-sentence titles
- Insight: Titles typically follow a standard length, consistent with the character count analysis.

3. Title mean word length
- Statistics: Mean ~ 7.8, Median ~7.7, Range: 3.5-17.5 words
- Distribution: Narrow distribution (7–9 characters) with both upper and lower outliers
- Insight: a frequent use of technical or academic vocabulary, which typically consists of longer, more complex terms.

In [11]:
df.info()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20972 entries, 0 to 20971
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID                    20972 non-null  int64
 1   TITLE                 20972 non-null  object
 2   ABSTRACT              20972 non-null  object
 3   Computer Science      20972 non-null  int64
 4   Physics               20972 non-null  int64
 5   Mathematics           20972 non-null  int64
 6   Statistics            20972 non-null  int64
 7   Quantitative Biology  20972 non-null  int64
 8   Quantitative Finance  20972 non-null  int64
dtypes: int64(7), object(2)
memory usage: 1.4+ MB

(20972, 9)

In [12]:
df.isnull().sum()
df.duplicated().sum()

np.int64(0)

In [14]:
label_columns = [
    "Computer Science",
    "Physics",
    "Mathematics",
    "Statistics",
    "Quantitative Biology",
    "Quantitative Finance"
]
df[label_columns].sum()

Computer Science        8594
Physics                 6013
Mathematics             5618
Statistics              5206
Quantitative Biology     587
Quantitative Finance     249
dtype: int64